// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://phoywy4h5jfljf26wuqfkhwzku.appsync-api.ap-south-1.amazonaws.com/graphql',
          region: 'ap-south-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-vwgojxdtxrhvlfum2ygeziu5lq'
        }
    }
};

export default config;