// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://i5ymvkibgvfoplptrztkkswfqq.appsync-api.ap-south-1.amazonaws.com/graphql',
          region: 'ap-south-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-4rc7sm6sbfehrkkikpic7ovuni'
        }
    }
};

export default config;