// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://ka5h6lt5efgdbio4erkwkpxlk4.appsync-api.ap-south-1.amazonaws.com/graphql',
          region: 'ap-south-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-zql7qijnbjhjndvquzeo6v42fy'
        }
    }
};

export default config;

